
select top 100 * from customer_behavior 

--Q1. What is the total revenue generated by male vs. female customers?

select sum(purchase_amount) as total_revenue ,gender from customer_behavior group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount
from customer_behavior
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_behavior)


-- Q3. Which are the top 5 products with the highest average review rating?
select  * 
from customer_behavior
order by review_rating desc


select top 5 item_purchased, round(AVG(review_rating),2) as avg_review_rating
from customer_behavior
group by item_purchased 
order by avg_review_rating desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select AVG(purchase_amount) avg_purchase_amt, shipping_type
from customer_behavior 
where shipping_type in ('Standard','Express')
group by shipping_type



--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select count(customer_id) as total_customer,
round(AVG(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue, 
subscription_status 
from customer_behavior
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?


select top 5 item_purchased,
	round(100*sum( case when discount_applied = 'Yes' then 1 else 0 end)/count(*) ,2) as discount_rate
from customer_behavior
group by item_purchased
order by  discount_rate desc



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer_behavior
)

select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
with item_count as (
select category,
item_purchased, 
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behavior
group by category,item_purchased
)
select item_rank,category,
item_purchased, total_orders
from item_count
where item_rank <=3




select category,
item_purchased, 
count(customer_id) as total_orders,
RANK() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behavior
group by category,item_purchased


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeat_buyers,subscription_status
from customer_behavior
where previous_purchases >5
group by subscription_status



--Q10. What is the revenue contribution of each age group? 

select sum(purchase_amount) as revenue, age_group
from customer_behavior
group by age_group
order by revenue desc

